version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: kek
      POSTGRES_PASSWORD: kek
      POSTGRES_DB: kek
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 1s
      timeout: 1s
      retries: 50
    ports:
      - "127.0.0.1:5432:5432"
